# Generated by Django 4.2.7 on 2023-12-03 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(choices=[('IT', 'IT technology'), ('Computer', 'Computer service'), ('Plumbing', 'Plumbing service'), ('Electician', 'Electrician service')], max_length=15)),
                ('master', models.ManyToManyField(limit_choices_to={'is_master': 'True'}, related_name='specific', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
