# Generated by Django 4.2.7 on 2023-12-02 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='service',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(default='Not assigned', limit_choices_to={'user__is_master': 'True'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
