# Generated by Django 4.2.7 on 2023-12-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_category_service_alter_order_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='service',
            field=models.CharField(max_length=20),
        ),
    ]
