# Generated by Django 4.2.7 on 2023-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meeting_time',
            field=models.DateTimeField(null=True),
        ),
    ]
